In [1]:
import numpy as np
import pandas as pd
import os
from classifier import GenreClassifier
import math

In [2]:
filepath = 'giantNP.csv'
ydata = pd.read_csv('project.csv')

In [3]:
topN = 50
numGenres = len(list(set(ydata['Genre'])))

In [4]:
set(ydata['Genre'])

{'Adventure',
 'Biography',
 'Essays',
 'Fantasy',
 'Fiction',
 'Historical Fiction',
 'Horror',
 'Mystery',
 'Romance'}

In [5]:
df = pd.read_csv('giantNP_Transpose.csv', header=None)

In [6]:
df.drop(0, axis=1, inplace=True)

In [7]:
df.shape

(374927, 42)

In [8]:
tfidf = df.to_numpy()
tfidf = tfidf.T

In [9]:
labels = ydata['Genre'].to_numpy()

In [10]:
prepro = np.argsort(tfidf, axis=1)[:,1:51]
prepro.shape

(42, 50)

In [11]:
temp = np.argsort(tfidf, axis=1)
for i in range(50):
    print(temp[0:20,i]-temp[0,i])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [12]:
print(prepro[:,0])

[249955 249955 249955 249955 249955 249955 249955 249955 249955 249955
 249955 249955 249955 249955 249955 249955 249955 249955 249955 249955
 245936 252525 252732 251329 266744 238021 247262 245581 248233 249587
 244787 246698 248386 247243 247120 249337 249743 243954 234437 246134
 233875 249345]


In [13]:
print(min(prepro[:,0]))
print(max(prepro[:,0]))

233875
266744


In [14]:
# os.system("python classifier.py")

voc = ['youdidntincludethevocab']*tfidf.shape[1]

In [19]:
gc = GenreClassifier(prepro[:22,:],None,voc,labels,numGenres,prepro.shape[1])

(9, 50)


In [20]:
answer = np.array(gc.KMeans(), dtype=object)

0
1


In [21]:
print(answer)
gc.centers

[list([]) list([]) list([]) list([]) list([])
 list([array([249955, 249954, 249953, 249952, 249951, 249950, 249949, 249948,
        249956, 249947, 249945, 249944, 249943, 249942, 249941, 249940,
        249939, 249938, 249946, 249957, 249958, 249959, 249978, 249977,
        249976, 249975, 249974, 249973, 249972, 249971, 249970, 249969,
        249968, 249967, 249966, 249965, 249964, 249963, 249962, 249961,
        249960, 249937, 249936, 249935, 249934, 249910, 249909, 249908,
        249907, 249906]), array([249955, 249954, 249953, 249952, 249951, 249950, 249949, 249948,
        249956, 249947, 249945, 249944, 249943, 249942, 249941, 249940,
        249939, 249938, 249946, 249957, 249958, 249959, 249978, 249977,
        249976, 249975, 249974, 249973, 249972, 249971, 249970, 249969,
        249968, 249967, 249966, 249965, 249964, 249963, 249962, 249961,
        249960, 249937, 249936, 249935, 249934, 249910, 249909, 249908,
        249907, 249906]), array([249955, 249954, 249953, 24

array([[248557.        , 248761.        , 250220.        ,
        251175.        , 250442.        , 245956.        ,
        249583.        , 248478.        , 247181.        ,
        249818.        , 248756.        , 249178.        ,
        252481.        , 246740.        , 248606.        ,
        246563.        , 247555.        , 250926.        ,
        247944.        , 251099.        , 249605.        ,
        246870.        , 251978.        , 250209.        ,
        252082.        , 247784.        , 246749.        ,
        252328.        , 247837.        , 250772.        ,
        247073.        , 246823.        , 250732.        ,
        247235.        , 246513.        , 249651.        ,
        251151.        , 248821.        , 247160.        ,
        250302.        , 246250.        , 251013.        ,
        251971.        , 248153.        , 251842.        ,
        247190.        , 249087.        , 247777.        ,
        250016.        , 246602.        ],
       [25026

In [18]:
if 

SyntaxError: invalid syntax (<ipython-input-18-774f1dd50554>, line 1)

In [ ]:
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from sklearn.metrics import silhouette_score

In [ ]:
model = KMeans(init="random", n_clusters=5, random_state=42).fit(prepro)

In [ ]:
model.cluster_centers_

In [ ]:
kmeans_kwargs = {
   ...:     "init": "random",
   ...:     "n_init": 10
   ...: }
   ...:
   ...: # A list holds the SSE values for each k
   ...: sse = []
   ...: for k in range(1, 14):
   ...:     kmeans = KMeans(n_clusters=k, **kmeans_kwargs)
   ...:     kmeans.fit(prepro)
   ...:     sse.append(kmeans.inertia_)
    
plt.plot(range(1, 14), sse)
plt.xticks(range(1, 14))
plt.xlabel("Number of Clusters")
plt.ylabel("SSE")
plt.show()

In [ ]:
silhouette_coefficients = []
   ...:
   ...: # Notice you start at 2 clusters for silhouette coefficient
   ...: for k in range(2, 11):
   ...:     kmeans = KMeans(n_clusters=k, **kmeans_kwargs)
   ...:     kmeans.fit(prepro)
   ...:     score = silhouette_score(df, kmeans.labels_)
   ...:     silhouette_coefficients.append(score)

 ...: plt.plot(range(2, 11), silhouette_coefficients)
   ...: plt.xticks(range(2, 11))
   ...: plt.xlabel("Number of Clusters")
   ...: plt.ylabel("Silhouette Coefficient")
   ...: plt.show()

In [ ]:
np.savetxt("cluster_centroids.csv", model.cluster_centers_, delimiter=",")

In [ ]:
centroids = pd.read_csv('cluster_centroids.csv', header=None)
centroids.shape

In [ ]:
data = pd.DataFrame(prepro)
data.shape

In [ ]:
assigned_clusters = []

for index_novel, each_row_novel in data.iterrows():
    ec_dist = []
    for index_centroid, each_row_centroid in centroids.iterrows():
        eculidean_dist = math.dist(each_row_novel, each_row_centroid)
        ec_dist.append(eculidean_dist)
    assigned_clusters.append([index_novel, ec_dist.index(min(ec_dist))])

In [ ]:
novel_names = pd.read_csv('project.csv')
novel_names

In [ ]:
novel_names['predicted_cluster'] = [i[1] for i in assigned_clusters]

In [ ]:
novel_names

In [ ]:
print(novel_names[novel_names['predicted_cluster'] == 2])

In [ ]:
novel_names.predicted_cluster.unique()