In [1]:
import numpy as np
import pandas as pd
import os
from classifier import GenreClassifier

In [2]:
filepath = 'giantNP.csv'
ydata = pd.read_csv('project.csv')

In [3]:
topN = 50
numGenres = len(list(set(ydata['Genre'])))

In [4]:
# df = pd.read_csv(filepath)
# print('done reading')
# tfidf = df.to_numpy()
tfidf = np.random.randint(1,300664,(41,50))

In [5]:
labels = ydata['Genre'].to_numpy()

In [6]:
prepro = np.argsort(tfidf, axis=1)[:,:topN]

In [7]:
# os.system("python classifier.py")

# voc = ['youdidntincludethevocab']*prepro.shape[1]

In [8]:
print(prepro.shape)

(41, 50)


In [9]:
gc = GenreClassifier(prepro,None,None,labels,numGenres,topN)

In [10]:
mt = np.concatenate(tuple([prepro]*9), axis=1)
print(mt.shape)
print(type(gc.xdata))
print(gc.xdata.shape)

(41, 450)
<class 'numpy.ndarray'>
(41, 50)


In [11]:
# gc.KMeans()

In [12]:

def KM(iterr=0):
    clusters = [[] for i in range(gc.K)]
    newcenters = np.zeros(gc.centers.shape)

    print(iterr)
#     print('center.shape'+str(gc.centers.shape))
#     print(gc.centers)
    #assume centers are KxD and xdata is NxD
    t = np.concatenate(tuple([gc.xdata]*gc.K), axis=1).reshape((gc.N*gc.K,gc.D))
    c = np.concatenate(tuple([gc.centers]*gc.N), axis=0).reshape((gc.N*gc.K,gc.D))
    dist = np.sum((t-c)**2,axis=1)
    dist = dist.reshape(gc.N,gc.K)
    
    for doc,cluster in enumerate(np.argmin(dist,axis=1)):
        clusters[cluster].append(gc.xdata[doc])
    
    for n,cluster in enumerate(clusters):
        if len(cluster) == 0:
            newcenters[n]=gc.centers[n]
        else:
            newcenters[n]=np.mean(np.asarray(cluster),axis=0)
    if (gc.centers == newcenters).all():
        return clusters
    gc.centers = newcenters
    return KM(iterr+1)

In [13]:
KM()

0
center.shape(9, 50)
[ 1 44  5 25 10 36 27 48  3  5 14  5 39 49 11 34 30 31 42 32 46 46 36 39
 10 46 39  2  7 48 40 25 13 44 41 28 34 12 45 32 14  3  4 34 36 23 32 27
 24 32]
1
center.shape(9, 50)
[ 1. 44.  5. 25. 10. 36. 27. 48.  3.  5. 14.  5. 39. 49. 11. 34. 30. 31.
 42. 32. 46. 46. 36. 39. 10. 46. 39.  2.  7. 48. 40. 25. 13. 44. 41. 28.
 34. 12. 45. 32. 14.  3.  4. 34. 36. 23. 32. 27. 24. 32.]


[[],
 [array([10,  5, 21,  2,  6, 24, 33,  4, 45, 41,  0, 40, 18, 11,  7, 25, 28,
         15, 19, 13,  3, 44, 23, 42, 37, 36, 48,  9, 47, 31, 43, 38, 39, 20,
         12, 49, 22, 32, 17,  1, 46, 27, 16, 30,  8, 29, 35, 34, 26, 14]),
  array([ 9, 34, 44, 22, 46,  4, 14, 24, 27, 17, 15, 12, 16, 11, 49, 30, 25,
         19, 23, 41, 33, 29,  3, 37, 35,  0, 38, 32,  5, 31, 48,  1, 42, 13,
         40,  7, 36, 39, 21, 45, 26,  6, 20,  8, 47, 28, 18,  2, 43, 10]),
  array([34, 14, 48, 15, 21, 11, 44,  5, 36, 33, 10,  7,  3, 28, 17, 38, 43,
         22,  2, 42, 25,  0,  8, 35, 24, 23, 31,  1, 49,  9, 47, 46, 32, 26,
          6,  4, 41, 16, 29, 39, 45, 27, 18, 20, 13, 40, 12, 30, 19, 37]),
  array([31, 24, 49,  1, 18,  2, 23,  9, 46, 43, 39, 22, 19, 37, 28, 42, 26,
         27, 32,  5, 12, 36, 11,  3,  0, 35, 47, 33, 17,  7, 13, 44, 30, 45,
         38, 41, 15, 25, 40,  4,  8, 20, 34, 48, 10, 16, 21, 29,  6, 14]),
  array([31, 39, 19,  1, 49, 14, 13, 44, 18, 43, 27, 33, 11, 34,  0, 21, 17,
  