In [1]:
import numpy as np
import pandas as pd
import os
from classifier import GenreClassifier
import math

In [2]:
filepath = 'giantNP.csv'
ydata = pd.read_csv('project.csv')

In [3]:
topN = 50
numGenres = len(list(set(ydata['Genre'])))

In [4]:
set(ydata['Genre'])

{'Adventure',
 'Biography',
 'Essays',
 'Fantasy',
 'Fiction',
 'Historical Fiction',
 'Horror',
 'Mystery',
 'Romance'}

In [5]:
df = pd.read_csv('giantNP_Transpose.csv', header=None)

In [6]:
df.drop(0, axis=1, inplace=True)

In [7]:
df.shape

(374927, 42)

In [8]:
tfidf = df.to_numpy()
tfidf = tfidf.T

In [9]:
labels = ydata['Genre'].to_numpy()

In [24]:
prepro = np.argsort(tfidf, axis=1)[:,1:51]
prepro.shape

(42, 50)

In [27]:
temp = np.argsort(tfidf, axis=1)
for i in range(50):
    print(temp[0:20,i]-temp[0,i])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [12]:
print(prepro[:,0])

[249948 249948 249948 249948 249948 249948 249948 249948 249948 249948
 249948 249948 249948 249948 249948 249948 249948 249948 249948 249948
 245929 252518 252725 251322 266737 238014 247255 245574 248226 249580
 244779 246691 248379 247236 247113 249330 249736 243947 234430 246127
 233868 249338]


In [13]:
print(min(prepro[:,0]))
print(max(prepro[:,0]))

233868
266737


In [14]:
# os.system("python classifier.py")

voc = ['youdidntincludethevocab']*tfidf.shape[1]

In [15]:
gc = GenreClassifier(prepro,None,voc,labels,numGenres,prepro.shape[1])

In [16]:
answer = np.array(gc.KMeans(), dtype=object)

0


ValueError: cannot reshape array of size 336 into shape (378,8)

In [ ]:
print(answer)
gc.centers

In [ ]:
if 

In [ ]:
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from sklearn.metrics import silhouette_score

In [ ]:
model = KMeans(init="random", n_clusters=5, random_state=42).fit(prepro)

In [ ]:
model.cluster_centers_

In [ ]:
kmeans_kwargs = {
   ...:     "init": "random",
   ...:     "n_init": 10
   ...: }
   ...:
   ...: # A list holds the SSE values for each k
   ...: sse = []
   ...: for k in range(1, 14):
   ...:     kmeans = KMeans(n_clusters=k, **kmeans_kwargs)
   ...:     kmeans.fit(prepro)
   ...:     sse.append(kmeans.inertia_)
    
plt.plot(range(1, 14), sse)
plt.xticks(range(1, 14))
plt.xlabel("Number of Clusters")
plt.ylabel("SSE")
plt.show()

In [ ]:
silhouette_coefficients = []
   ...:
   ...: # Notice you start at 2 clusters for silhouette coefficient
   ...: for k in range(2, 11):
   ...:     kmeans = KMeans(n_clusters=k, **kmeans_kwargs)
   ...:     kmeans.fit(prepro)
   ...:     score = silhouette_score(df, kmeans.labels_)
   ...:     silhouette_coefficients.append(score)

 ...: plt.plot(range(2, 11), silhouette_coefficients)
   ...: plt.xticks(range(2, 11))
   ...: plt.xlabel("Number of Clusters")
   ...: plt.ylabel("Silhouette Coefficient")
   ...: plt.show()

In [ ]:
np.savetxt("cluster_centroids.csv", model.cluster_centers_, delimiter=",")

In [ ]:
centroids = pd.read_csv('cluster_centroids.csv', header=None)
centroids.shape

In [ ]:
data = pd.DataFrame(prepro)
data.shape

In [ ]:
assigned_clusters = []

for index_novel, each_row_novel in data.iterrows():
    ec_dist = []
    for index_centroid, each_row_centroid in centroids.iterrows():
        eculidean_dist = math.dist(each_row_novel, each_row_centroid)
        ec_dist.append(eculidean_dist)
    assigned_clusters.append([index_novel, ec_dist.index(min(ec_dist))])

In [ ]:
novel_names = pd.read_csv('project.csv')
novel_names

In [ ]:
novel_names['predicted_cluster'] = [i[1] for i in assigned_clusters]

In [ ]:
novel_names

In [ ]:
print(novel_names[novel_names['predicted_cluster'] == 2])

In [ ]:
novel_names.predicted_cluster.unique()